// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPgidcOfYUr1WNo4RAHCJm_vWjqKmLgaM',
    appId: '1:26758504344:web:7cd377545ddf21234395ed',
    messagingSenderId: '26758504344',
    projectId: 'recipeapp-98710',
    authDomain: 'recipeapp-98710.firebaseapp.com',
    databaseURL: 'https://recipeapp-98710-default-rtdb.firebaseio.com',
    storageBucket: 'recipeapp-98710.appspot.com',
    measurementId: 'G-WGD9VD8YSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBahNuljipTuDjE0etUWleqkZ7bNvoaR-A',
    appId: '1:26758504344:android:746abba9b7154aa44395ed',
    messagingSenderId: '26758504344',
    projectId: 'recipeapp-98710',
    databaseURL: 'https://recipeapp-98710-default-rtdb.firebaseio.com',
    storageBucket: 'recipeapp-98710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNx-Zd32Sb-IcTaPCUqyxdH6HjaOrEvbI',
    appId: '1:26758504344:ios:8276e28321c744134395ed',
    messagingSenderId: '26758504344',
    projectId: 'recipeapp-98710',
    databaseURL: 'https://recipeapp-98710-default-rtdb.firebaseio.com',
    storageBucket: 'recipeapp-98710.appspot.com',
    iosBundleId: 'com.example.flutterGithubWorkflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNx-Zd32Sb-IcTaPCUqyxdH6HjaOrEvbI',
    appId: '1:26758504344:ios:6e95ed461de54fd04395ed',
    messagingSenderId: '26758504344',
    projectId: 'recipeapp-98710',
    databaseURL: 'https://recipeapp-98710-default-rtdb.firebaseio.com',
    storageBucket: 'recipeapp-98710.appspot.com',
    iosBundleId: 'com.example.flutterGithubWorkflow.RunnerTests',
  );
}
